INSERT INTO article(title, content) VALUES ('가가가가', '1111');
INSERT INTO article(title, content) VALUES ('나나나나', '2222');
INSERT INTO article(title, content) VALUES ('다다다다', '3333');

INSERT INTO article(title, content) VALUES ('당신의 인생 영화는?', '댓글');
INSERT INTO article(title, content) VALUES ('당신의 소울 푸드는?', '댓글');
INSERT INTO article(title, content) VALUES ('당신의 취미는?', '댓글');

INSERT INTO comment(article_id, nickname, body) VALUES (4,'Kim', '해리포터 시리즈');
INSERT INTO comment(article_id, nickname, body) VALUES (4,'Lee', '비긴어게인');
INSERT INTO comment(article_id, nickname, body) VALUES (4,'Park', '나니아 연대기');

INSERT INTO comment(article_id, nickname, body) VALUES (5,'Kim', '치킨');
INSERT INTO comment(article_id, nickname, body) VALUES (5,'Lee', '떡볶이');
INSERT INTO comment(article_id, nickname, body) VALUES (5,'Park', '스시');

INSERT INTO comment(article_id, nickname, body) VALUES (6,'Kim', '독서');
INSERT INTO comment(article_id, nickname, body) VALUES (6,'Lee', '운동');
INSERT INTO comment(article_id, nickname, body) VALUES (6,'Park', '조깅');

--INSERT INTO member(email, password) VALUES ('abcd@email.com', '1111');
--INSERT INTO member(email, password) VALUES ('1234@email.com', '2222');
--INSERT INTO member(email, password) VALUES ('test@email.com', '3333');

--CREATE TABLE coffee (
--    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
--    name varchar(255),
--    price integer,
--    primary key (id)
--);

--CREATE TABLE burgers (
--    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
--    name VARCHAR(50), -- 이름(최대 50글자)
--    price INTEGER, -- 가격(숫자)
--    gram INTEGER, -- 무게(숫자)
--    kcal INTEGER, -- 열랑(숫자)
--    protein INTEGER, -- 단백질량(숫자)
--    PRIMARY KEY (id)
--);

--INSERT INTO burgers (id, name, price, gram,kcal, protein)
--VALUES
--(1, '행운버거 골드', 5300, 222, 540, 25),
--(2, '트리플 치즈버거', 6300, 219, 619, 36),
--(3, '빅맥', 5300, 223, 583, 27);

-- 11장 셀프체크 데이터 추가
INSERT INTO coffee(name, price) VALUES('아메리카노', '4500');
INSERT INTO coffee(name, price) VALUES('카페라떼', '5000');
INSERT INTO coffee(name, price) VALUES('카페모카', '5500');